name: drift_clear_learn
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk:  '>=3.6.0 < 4.0.0'    

dependencies:
  flutter:
    sdk: flutter
  #for Drift
  drift: ^2.15.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #for Drift
  build_runner: ^2.4.8
  drift_dev: ^2.15.0


flutter:
  uses-material-design: true
